#!/bin/sh /etc/rc.common
# (C) 2024 rtaserver

START=99
STOP=15

start_service() {
    if pidof core-manager.sh > /dev/null; then
        echo "RakitanManager is already running."
    else
        if [ "$(uci get rakitanmanager.cfg.enabled)" = "1" ]; then
            /usr/share/rakitanmanager/core-manager.sh -s
        fi        
    fi
}

start() {
    start_service
}

stop() {
    # If you have a stop function, you can define it here.
    :
}

restart() {
    # If you want to implement restart functionality, you can define it here.
    :
}