#!/bin/sh /etc/rc.common
# (C) 2024 rtaserver

START=99
STOP=15

PROGMAIN="/usr/bin/rakitanmanager.sh"
PROGBOT="/usr/bin/rakitanmanagerbot.sh"

start_service () {
    PID1=$(pgrep -f ${PROGMAIN})
    if [ -z "$PID1" ]  ; then
        if [ "$(uci get rakitanmanager.cfg.startup)" = "1" ]; then
            sleep 1 && $PROGMAIN -s
        fi
    fi
}